version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "next"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "next"
    versioning-strategy: "increase"
  - package-ecosystem: "npm"
    directory: "/micromark"
    schedule:
      interval: "daily"
    target-branch: "next"
    versioning-strategy: "increase"
